server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: rates-service
          uri: lb://rates-service
          predicates:
            - Path=/api/rates/**
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/reservation/**
        - id: rack-service
          uri: lb://rack-service
          predicates:
            - Path=/api/rack/**
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/api/report/**
        - id: loyaltydiscount-service
          uri: lb://loyaltydiscount-service
          predicates:
            - Path=/api/loyalty/**
        - id: peoplediscount-service
          uri: lb://peoplediscount-service
          predicates:
            - Path=/api/people/**
        - id: specialdaydiscount-service
          uri: lb://specialdaydiscount-service
          predicates:
            - Path=/api/specialday/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always