server:
  port: 0
spring:
  application:
    name: rates-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:rates-db-service}:${DB_PORT:5432}/${DB_DBNAME:rates-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${random.value}
    hostname: ${HOSTNAME:rates-service}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always