server:
  port: ${SERVER_PORT}
spring:
  application:
    name: report-service
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/