server:
  port: ${SERVER_PORT}
spring:
  application:
    name: specialdaydiscount-service
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DBNAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/
    instance:
        instance-id: ${spring.application.name}:${server.port}
        hostname: ${HOSTNAME}