apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-deployment
  labels:
    app: eureka-server-deployment
spec:
  selector:
    matchLabels:
      app: eureka-server-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-server-deployment
    spec:
      containers:
        - name: eureka-server
          image: claubells/eureka-server
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "false"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "eureka-server-service"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://eureka-server-service:8761/eureka/"
            - name: EUREKA_SERVER_ENABLE_SELF_PRESERVATION
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server-service
  labels:
    app: eureka-server-service
spec:
  selector:
    app: eureka-server-deployment
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: LoadBalancer