apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server-deployment
  labels:
    app: gateway-server-deployment
spec:
  selector:
    matchLabels:
      app: gateway-server-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-server-deployment
    spec:
      containers:
        - name: gateway-server
          image: claubells/gateway-server
          ports:
            - containerPort: 8080
          env:
            - name: CONFIG_SERVER_HOST
              value: "config-service"
            - name: EUREKA_HOST
              value: "eureka-service"
            - name: EUREKA_PORT
              value: "8761"
            - name: INSTANCE_HOSTNAME
              value: "gateway-service"
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_PROFILES_ACTIVE
              value: "gateway-service"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-server-service
  labels:
    app: gateway-server-service
spec:
  selector:
    app: gateway-server-deployment
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer