apiVersion: apps/v1
kind: Deployment
metadata:
  name: peoplediscount-deployment
  labels:
    app: peoplediscount-deployment
spec:
  selector:
    matchLabels:
      app: peoplediscount-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: peoplediscount-deployment
    spec:
      containers:
        - name: peoplediscount-service
          image: claubells/peoplediscount-service
          ports:
            - containerPort: 8092
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_PEOPLE
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_PEOPLE
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_PEOPLE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_PEOPLE
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_PEOPLE
---
apiVersion: v1
kind: Service
metadata:
  name: peoplediscount-service
  labels:
    app: peoplediscount-deployment
spec:
  selector:
    app: peoplediscount-deployment
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 8092
  type: ClusterIP