apiVersion: apps/v1
kind: Deployment
metadata:
  name: rack-deployment
  labels:
    app: rack-deployment
spec:
  selector:
    matchLabels:
      app: rack-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: rack-deployment
    spec:
      containers:
        - name: rack-service
          image: claubells/rack-service
          ports:
            - containerPort: 8093
---
apiVersion: v1
kind: Service
metadata:
  name: rack-service
  labels:
    app: rack-deployment
spec:
  selector:
    app: rack-deployment
  ports:
    - protocol: TCP
      port: 8093
      targetPort: 8093
  type: ClusterIP