apiVersion: apps/v1
kind: Deployment
metadata:
  name: rack-deployment
  labels:
    app: rack-deployment
spec:
  selector:
    matchLabels:
      app: rack-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: rack-deployment
    spec:
      containers:
        - name: rack-service
          image: claubells/rack-service
          env:
            - name: SERVER_PORT
              value: "0"
            - name: CONFIG_SERVER_HOST
              value: "config-server-service"
            - name: EUREKA_HOST
              value: "eureka-server-service"
            - name: EUREKA_PORT
              value: "8761"
            - name: INSTANCE_HOSTNAME
              value: "rack-service"
---
apiVersion: v1
kind: Service
metadata:
  name: rack-service
  labels:
    app: rack-deployment
spec:
  clusterIP: None
  selector:
    app: rack-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080