apiVersion: apps/v1
kind: Deployment
metadata:
  name: rates-deployment
  labels:
    app: rates-deployment
spec:
  selector:
    matchLabels:
      app: rates-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: rates-deployment
    spec:
      containers:
        - name: rates-service
          image: claubells/rates-service
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_RATES
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_RATES
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_RATES
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_RATES
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_RATES
            - name: CONFIG_SERVER_HOST
              value: "config-server-service"
            - name: EUREKA_HOST
              value: "eureka-server-service"
            - name: EUREKA_PORT
              value: "8761"
            - name: INSTANCE_HOSTNAME
              value: totalcost-service
---
apiVersion: v1
kind: Service
metadata:
  name: rates-service
  labels:
    app: rates-deployment
spec:
  clusterIP: None
  selector:
    app: rates-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080