apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-deployment
  labels:
    app: report-deployment
spec:
  selector:
    matchLabels:
      app: report-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: report-deployment
    spec:
      containers:
        - name: report-service
          image: claubells/report-service
          env:
            - name: CONFIG_SERVER_HOST
              value: "config-server"
            - name: EUREKA_HOST
              value: "eureka-server"
            - name: EUREKA_PORT
              value: "8761"
            - name: INSTANCE_HOSTNAME
              value: totalcost-service

---
apiVersion: v1
kind: Service
metadata:
  name: report-service
  labels:
    app: report-deployment
spec:
  selector:
    clusterIP: None
    app: report-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080