apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-deployment
  labels:
    app: report-deployment
spec:
  selector:
    matchLabels:
      app: report-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: report-deployment
    spec:
      containers:
        - name: report-service
          image: claubells/report-service
          env:
            - name: SERVER_PORT
              value: "0"
            - name: CONFIG_SERVER_HOST
              value: "config-server-service"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-server-service:8888"
            - name: EUREKA_HOST
              value: "eureka-server-service"
            - name: EUREKA_PORT
              value: "8761"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server-service:8761/eureka/"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://eureka-server-service:8761/eureka/"
            - name: INSTANCE_HOSTNAME
              value: "report-service"

---
apiVersion: v1
kind: Service
metadata:
  name: report-service
  labels:
    app: report-deployment
spec:
  clusterIP: None
  selector:
    app: report-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080