apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-deployment
  labels:
    app: report-deployment
spec:
  selector:
    matchLabels:
      app: report-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: report-deployment
    spec:
      containers:
        - name: report-service
          image: claubells/report-service
          ports:
            - containerPort: 8095
---
apiVersion: v1
kind: Service
metadata:
  name: report-service
  labels:
    app: report-deployment
spec:
  selector:
    app: report-deployment
  ports:
    - protocol: TCP
      port: 8095
      targetPort: 8095
  type: ClusterIP