apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-deployment
  labels:
    app: reservation-deployment
spec:
  selector:
    matchLabels:
      app: reservation-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: reservation-deployment
    spec:
      containers:
        - name: reservation-service
          image: claubells/reservation-service
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_RESERVATION
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_RESERVATION
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_RESERVATION
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_RESERVATION
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_RESERVATION
            - name: CONFIG_SERVER_HOST
              value: "config-server"
            - name: EUREKA_HOST
              value: "eureka-server"
            - name: EUREKA_PORT
              value: "8761"
            - name: INSTANCE_HOSTNAME
              value: totalcost-service
---
apiVersion: v1
kind: Service
metadata:
  name: reservation-service
  labels:
    app: reservation-deployment
spec:
  selector:
    clusterIP: None
    app: reservation-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080