apiVersion: apps/v1
kind: Deployment
metadata:
  name: specialdaydiscount-deployment
  labels:
    app: specialdaydiscount-deployment
spec:
  selector:
    matchLabels:
      app: specialdaydiscount-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: specialdaydiscount-deployment
    spec:
      containers:
        - name: specialdaydiscount-service
          image: claubells/loyaltydiscount-service
          ports:
            - containerPort: 8097
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_HOLIDAYS
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_HOLIDAYS
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_HOLIDAYS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_HOLIDAYS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_HOLIDAYS
---
apiVersion: v1
kind: Service
metadata:
  name: specialdaydiscount-service
  labels:
    app: specialdaydiscount-deployment
spec:
  selector:
    app: specialdaydiscount-deployment
  ports:
    - protocol: TCP
      port: 8097
      targetPort: 8097
  type: ClusterIP