apiVersion: apps/v1
kind: Deployment
metadata:
  name: specialdaydiscount-deployment
  labels:
    app: specialdaydiscount-deployment
spec:
  selector:
    matchLabels:
      app: specialdaydiscount-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: specialdaydiscount-deployment
    spec:
      containers:
        - name: specialdaydiscount-service
          image: claubells/specialdaydiscount-service
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_HOLIDAYS
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_HOLIDAYS
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_HOLIDAYS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_HOLIDAYS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_HOLIDAYS
            - name: CONFIG_SERVER_HOST
              value: "config-server-service"
            - name: EUREKA_HOST
              value: "eureka-server-service"
            - name: EUREKA_PORT
              value: "8761"
            - name: INSTANCE_HOSTNAME
              value: "specialdaydiscount-service"
---
apiVersion: v1
kind: Service
metadata:
  name: specialdaydiscount-service
  labels:
    app: specialdaydiscount-deployment
spec:
  clusterIP: None
  selector:
    app: specialdaydiscount-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080