server:
    port: 8888
spring:
    cloud:
        config:
            server:
                git:
                    default-label: main
                    uri: https://github.com/claubells/karting2
                    search-paths: backend/config-data
    application:
        name: config-server