apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyaltydiscount-deployment
  labels:
    app: loyaltydiscount-deployment
spec:
  selector:
    matchLabels:
      app: loyaltydiscount-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: loyaltydiscount-deployment
    spec:
      containers:
        - name: loyaltydiscount-service
          image: claubells/loyaltydiscount-service
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_LOYALTY
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_LOYALTY
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_LOYALTY
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_LOYALTY
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_LOYALTY